version: '3.5'

services: 
  portainer:
    image: portainer/portainer
    container_name: portainer
    ports: 
      - "9000:9000"
    volumes: 
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./volumes/data:/data"
    restart: always